language: python
python:
    - "3.6"
    - "3.7"
    - "3.8.3"
cache: pip
install: 
    - pip install .[test]
before_script:
    - flake8 .
    - black --check .
script:
    - python setup.py test --pytest-args "tests/ --cov=./"
after_success:
  - codecov
branches:
  only:
    - master